# Copyright 2026 African Vibe Online Shop (AVOS)
# SPDX-License-Identifier: Apache-2.0

FROM mcr.microsoft.com/dotnet/sdk:10.0-noble

LABEL org.opencontainers.image.title="AVOS Cart Service (debug)"

WORKDIR /app
COPY . ./
RUN dotnet restore cartservice.csproj

ENV ASPNETCORE_ENVIRONMENT=Development \
    ASPNETCORE_HTTP_PORTS=7070 \
    CART_STORE=memory \
    ENABLE_OTEL=false

EXPOSE 7070
ENTRYPOINT ["dotnet", "run", "--no-restore", "--project", "cartservice.csproj"]
