// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v7.35.1
// source: shoppingassistant.proto

package hipstershop

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ShoppingAssistantService_GetRecommendations_FullMethodName = "/avos.shoppingassistant.v1.ShoppingAssistantService/GetRecommendations"
)

// ShoppingAssistantServiceClient is the client API for ShoppingAssistantService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ShoppingAssistantService recommends AVOS catalog products using a customer's
// request and an optional room or style image.
type ShoppingAssistantServiceClient interface {
	GetRecommendations(ctx context.Context, in *ShoppingAssistantRequest, opts ...grpc.CallOption) (*ShoppingAssistantResponse, error)
}

type shoppingAssistantServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewShoppingAssistantServiceClient(cc grpc.ClientConnInterface) ShoppingAssistantServiceClient {
	return &shoppingAssistantServiceClient{cc}
}

func (c *shoppingAssistantServiceClient) GetRecommendations(ctx context.Context, in *ShoppingAssistantRequest, opts ...grpc.CallOption) (*ShoppingAssistantResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ShoppingAssistantResponse)
	err := c.cc.Invoke(ctx, ShoppingAssistantService_GetRecommendations_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ShoppingAssistantServiceServer is the server API for ShoppingAssistantService service.
// All implementations must embed UnimplementedShoppingAssistantServiceServer
// for forward compatibility.
//
// ShoppingAssistantService recommends AVOS catalog products using a customer's
// request and an optional room or style image.
type ShoppingAssistantServiceServer interface {
	GetRecommendations(context.Context, *ShoppingAssistantRequest) (*ShoppingAssistantResponse, error)
	mustEmbedUnimplementedShoppingAssistantServiceServer()
}

// UnimplementedShoppingAssistantServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedShoppingAssistantServiceServer struct{}

func (UnimplementedShoppingAssistantServiceServer) GetRecommendations(context.Context, *ShoppingAssistantRequest) (*ShoppingAssistantResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRecommendations not implemented")
}
func (UnimplementedShoppingAssistantServiceServer) mustEmbedUnimplementedShoppingAssistantServiceServer() {
}
func (UnimplementedShoppingAssistantServiceServer) testEmbeddedByValue() {}

// UnsafeShoppingAssistantServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ShoppingAssistantServiceServer will
// result in compilation errors.
type UnsafeShoppingAssistantServiceServer interface {
	mustEmbedUnimplementedShoppingAssistantServiceServer()
}

func RegisterShoppingAssistantServiceServer(s grpc.ServiceRegistrar, srv ShoppingAssistantServiceServer) {
	// If the following call pancis, it indicates UnimplementedShoppingAssistantServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ShoppingAssistantService_ServiceDesc, srv)
}

func _ShoppingAssistantService_GetRecommendations_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ShoppingAssistantRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShoppingAssistantServiceServer).GetRecommendations(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ShoppingAssistantService_GetRecommendations_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShoppingAssistantServiceServer).GetRecommendations(ctx, req.(*ShoppingAssistantRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ShoppingAssistantService_ServiceDesc is the grpc.ServiceDesc for ShoppingAssistantService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ShoppingAssistantService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "avos.shoppingassistant.v1.ShoppingAssistantService",
	HandlerType: (*ShoppingAssistantServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetRecommendations",
			Handler:    _ShoppingAssistantService_GetRecommendations_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "shoppingassistant.proto",
}
