// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: shoppingassistant.proto

package hipstershop

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ShoppingAssistantRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	UserId         string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Prompt         string                 `protobuf:"bytes,2,opt,name=prompt,proto3" json:"prompt,omitempty"`
	Image          []byte                 `protobuf:"bytes,3,opt,name=image,proto3" json:"image,omitempty"`
	ImageMediaType string                 `protobuf:"bytes,4,opt,name=image_media_type,json=imageMediaType,proto3" json:"image_media_type,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ShoppingAssistantRequest) Reset() {
	*x = ShoppingAssistantRequest{}
	mi := &file_shoppingassistant_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShoppingAssistantRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShoppingAssistantRequest) ProtoMessage() {}

func (x *ShoppingAssistantRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shoppingassistant_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShoppingAssistantRequest.ProtoReflect.Descriptor instead.
func (*ShoppingAssistantRequest) Descriptor() ([]byte, []int) {
	return file_shoppingassistant_proto_rawDescGZIP(), []int{0}
}

func (x *ShoppingAssistantRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ShoppingAssistantRequest) GetPrompt() string {
	if x != nil {
		return x.Prompt
	}
	return ""
}

func (x *ShoppingAssistantRequest) GetImage() []byte {
	if x != nil {
		return x.Image
	}
	return nil
}

func (x *ShoppingAssistantRequest) GetImageMediaType() string {
	if x != nil {
		return x.ImageMediaType
	}
	return ""
}

type ShoppingAssistantResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Content       string                 `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	ProductIds    []string               `protobuf:"bytes,2,rep,name=product_ids,json=productIds,proto3" json:"product_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShoppingAssistantResponse) Reset() {
	*x = ShoppingAssistantResponse{}
	mi := &file_shoppingassistant_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShoppingAssistantResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShoppingAssistantResponse) ProtoMessage() {}

func (x *ShoppingAssistantResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shoppingassistant_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShoppingAssistantResponse.ProtoReflect.Descriptor instead.
func (*ShoppingAssistantResponse) Descriptor() ([]byte, []int) {
	return file_shoppingassistant_proto_rawDescGZIP(), []int{1}
}

func (x *ShoppingAssistantResponse) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *ShoppingAssistantResponse) GetProductIds() []string {
	if x != nil {
		return x.ProductIds
	}
	return nil
}

var File_shoppingassistant_proto protoreflect.FileDescriptor

const file_shoppingassistant_proto_rawDesc = "" +
	"\n" +
	"\x17shoppingassistant.proto\x12\x19avos.shoppingassistant.v1\"\x8b\x01\n" +
	"\x18ShoppingAssistantRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x16\n" +
	"\x06prompt\x18\x02 \x01(\tR\x06prompt\x12\x14\n" +
	"\x05image\x18\x03 \x01(\fR\x05image\x12(\n" +
	"\x10image_media_type\x18\x04 \x01(\tR\x0eimageMediaType\"V\n" +
	"\x19ShoppingAssistantResponse\x12\x18\n" +
	"\acontent\x18\x01 \x01(\tR\acontent\x12\x1f\n" +
	"\vproduct_ids\x18\x02 \x03(\tR\n" +
	"productIds2\x9e\x01\n" +
	"\x18ShoppingAssistantService\x12\x81\x01\n" +
	"\x12GetRecommendations\x123.avos.shoppingassistant.v1.ShoppingAssistantRequest\x1a4.avos.shoppingassistant.v1.ShoppingAssistantResponse\"\x00BXZVgithub.com/Gabinsime75/African-Vibe-Online-Shop-AVOS/src/frontend/genproto;hipstershopb\x06proto3"

var (
	file_shoppingassistant_proto_rawDescOnce sync.Once
	file_shoppingassistant_proto_rawDescData []byte
)

func file_shoppingassistant_proto_rawDescGZIP() []byte {
	file_shoppingassistant_proto_rawDescOnce.Do(func() {
		file_shoppingassistant_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_shoppingassistant_proto_rawDesc), len(file_shoppingassistant_proto_rawDesc)))
	})
	return file_shoppingassistant_proto_rawDescData
}

var file_shoppingassistant_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_shoppingassistant_proto_goTypes = []any{
	(*ShoppingAssistantRequest)(nil),  // 0: avos.shoppingassistant.v1.ShoppingAssistantRequest
	(*ShoppingAssistantResponse)(nil), // 1: avos.shoppingassistant.v1.ShoppingAssistantResponse
}
var file_shoppingassistant_proto_depIdxs = []int32{
	0, // 0: avos.shoppingassistant.v1.ShoppingAssistantService.GetRecommendations:input_type -> avos.shoppingassistant.v1.ShoppingAssistantRequest
	1, // 1: avos.shoppingassistant.v1.ShoppingAssistantService.GetRecommendations:output_type -> avos.shoppingassistant.v1.ShoppingAssistantResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_shoppingassistant_proto_init() }
func file_shoppingassistant_proto_init() {
	if File_shoppingassistant_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_shoppingassistant_proto_rawDesc), len(file_shoppingassistant_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_shoppingassistant_proto_goTypes,
		DependencyIndexes: file_shoppingassistant_proto_depIdxs,
		MessageInfos:      file_shoppingassistant_proto_msgTypes,
	}.Build()
	File_shoppingassistant_proto = out.File
	file_shoppingassistant_proto_goTypes = nil
	file_shoppingassistant_proto_depIdxs = nil
}
