# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: shoppingassistant.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'shoppingassistant.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17shoppingassistant.proto\x12\x19\x61vos.shoppingassistant.v1\"d\n\x18ShoppingAssistantRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x0e\n\x06prompt\x18\x02 \x01(\t\x12\r\n\x05image\x18\x03 \x01(\x0c\x12\x18\n\x10image_media_type\x18\x04 \x01(\t\"A\n\x19ShoppingAssistantResponse\x12\x0f\n\x07\x63ontent\x18\x01 \x01(\t\x12\x13\n\x0bproduct_ids\x18\x02 \x03(\t2\x9e\x01\n\x18ShoppingAssistantService\x12\x81\x01\n\x12GetRecommendations\x12\x33.avos.shoppingassistant.v1.ShoppingAssistantRequest\x1a\x34.avos.shoppingassistant.v1.ShoppingAssistantResponse\"\x00\x42XZVgithub.com/Gabinsime75/African-Vibe-Online-Shop-AVOS/src/frontend/genproto;hipstershopb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'shoppingassistant_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'ZVgithub.com/Gabinsime75/African-Vibe-Online-Shop-AVOS/src/frontend/genproto;hipstershop'
  _globals['_SHOPPINGASSISTANTREQUEST']._serialized_start=54
  _globals['_SHOPPINGASSISTANTREQUEST']._serialized_end=154
  _globals['_SHOPPINGASSISTANTRESPONSE']._serialized_start=156
  _globals['_SHOPPINGASSISTANTRESPONSE']._serialized_end=221
  _globals['_SHOPPINGASSISTANTSERVICE']._serialized_start=224
  _globals['_SHOPPINGASSISTANTSERVICE']._serialized_end=382
# @@protoc_insertion_point(module_scope)
